version: '3.3'

services:
  spring-boot:
    container_name: dc-spring-boot-docker-debug
    build: .
    ports:
      - '8080:8080'
      - '5005:5005'
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
